# Inspecting ranks:
# prog = "dungeons raided";arr=Player.where(:last_active_at.gt => Time.now - 6.months).pluck(:progress).map{ |pr| pr[prog] || 0 }.sort

orders:
  all:
    induction_title: You've been inducted into an Order!
    advancement_title: You've advanced in an Order!
    peer_induction_message: has been inducted into the
    peer_advancement_message: has advanced within the

  Order of the Crow:
    induction_message: Your many journeys into the unknown have caught the attention of the Order of the Crow! Such wanderlust and adventure shall not go unnoticed. We invite you to join our ranks.
    advancement_message: Your continued pursuit of exploration pleases the council of the Order of the Crow! We have advanced your position within our ranks to honor your achievements.
    key: crow
    tiers:
      - requirements:
          level: 20
          'progress/chunks explored': 5000
          'progress/teleporters discovered': 25
      - requirements:
          level: 30
          'progress/chunks explored': 10000
          'progress/teleporters discovered': 50
      - requirements:
          level: 40
          'progress/chunks explored': 20000
          'progress/teleporters discovered': 100
      - requirements:
          level: 50
          'progress/chunks explored': 40000
          'progress/teleporters discovered': 200
      - requirements:
          level: 60
          'progress/chunks explored': 80000
          'progress/teleporters discovered': 400

  Order of the Lion:
    induction_message: Your prowess in battle and steadfast constitution has caught the attention of the Order of the Lion! We invite you to join our ranks of warriors, soldiers, and students of war.
    advancement_message: Your unquenched spirit in the face of danger pleases the council of the Order of the Lion! We have promoted you within our ranks to honor your martial accomplishments.
    key: lion
    tiers:
      - requirements:
          level: 20
          'progress/creatures killed': 5000
          'players_killed': 25
          'progress/dungeons raided': 500

      - requirements:
          level: 30
          'progress/creatures killed': 5000
          'progress/automata killed': 5000
          'players_killed': 50
          'progress/dungeons raided': 1000

      - requirements:
          level: 40
          'progress/creatures killed': 5000
          'progress/automata killed': 5000
          'progress/supernatural killed': 5000
          'players_killed': 100
          'progress/dungeons raided': 2000
          'progress/inhibitors activated': 25

      - requirements:
          level: 50
          'progress/creatures killed': 5000
          'progress/automata killed': 5000
          'progress/supernatural killed': 5000
          'progress/brains killed': 5000
          'players_killed': 200
          'progress/dungeons raided': 4000
          'progress/inhibitors activated': 50

      - requirements:
          level: 60
          'progress/creatures killed': 5000
          'progress/automata killed': 5000
          'progress/supernatural killed': 5000
          'progress/brains killed': 5000
          'brain_lords_killed': 100
          'players_killed': 400
          'progress/dungeons raided': 4000
          'progress/inhibitors activated': 100

  Order of the Moon:
    induction_message: Your financial support of Deepworld has caught the attention of the Order of the Moon! You are an important part of helping Deepworld thrive and we salute you.
    advancement_message: Your continued support of Deepworld pleases the council of the Order of the Moon! We have advanced your position within our ranks to honor your contributions.
    key: moon
    hidden: true
    tiers:
      - requirements:
          'crowns_spent': 1000
      - requirements:
          'crowns_spent': 2000
      - requirements:
          'crowns_spent': 4000
      - requirements:
          'crowns_spent': 8000
      - requirements:
          'crowns_spent': 16000
