name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
    paths:
      - .github/workflows/build.yml
      - deepworld-config
      - api/**
      - gameserver/**
      - shared/**
      - src/**
      - build.gradle
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: brainwine
        path: build/dist/brainwine.jar
        retention-days: 7
